### ISSUE TITLE
No mapbox basemap visible from Justin's browser

### ISSUE THREAD

**Issue by hickman** [gina-alaska/ubermap#12]
https://www.mapbox.com/mapbox.js/example/v1.0.0/ displays for Justin but still no mapbox basemap in the atlas.

**Comment by teknofire** [comment]
I guess next step to debug this would be to have him open the javascript console in his browser and see if it lists any errors

![image](https://cloud.githubusercontent.com/assets/3766/15483075/62df8ff0-20df-11e6-830d-e70763adfb05.png)

![all renewable energy fund projects 2016-05-23 12-11-30](https://cloud.githubusercontent.com/assets/3766/15483138/a7efb1c4-20df-11e6-9f51-ae92ab417f44.png)

**Comment by hickman** [comment]
Could you invite Justin Crowther to this repo so he can take a look at this directly? jcrowther@aidea.org
