### ISSUE TITLE
Ability to scroll map legends in multimap

### ISSUE THREAD

**Issue by hickman** [gina-alaska/ubermap#9]
If there are too many maps in a multimap, the topmost legend entries are not accessible.  Attached screenshot shows the legend extending beyond the top of the map frame which makes it impossible to compress the topmost map legend.  

![aea glynx gina alaska edu altas_legend_problem](https://cloud.githubusercontent.com/assets/1228808/15023233/2288138a-11dc-11e6-87d9-373a8e1347db.png)

**Comment by teknofire** [comment]
I pushed this to be a sidebar with scrolling for the multimap views.  The previous single map views still behave the same as before

**Comment by hickman** [comment]
Works great!
